baseURL = 'tghd.link'
languageCode = 'en-us'
title = 'Elias Braun'
copyright = 'Elias Braun'
theme = ['gokarna']
enableEmoji = true

pygmentsStyle = "monokai"

[params]
   	footer = 'Elias Braun'
   	description = '17 year old student from Germany'
	avatarURL = 'img/avatar.jpg'
	AvaterAltText = 'Avatar'
	avaterSize = 'size-m'
	ShowBackToTopButton = true
	customHeadHTML = """
    		<!-- KaTeX -->
    		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    		<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    		<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    		<script>
      			document.addEventListener("DOMContentLoaded", function() {
       			renderMathInElement(document.body, {
          			// customised options
          			// • auto-render specific keys, e.g.:
          			delimiters: [
            				{left: '$$', right: '$$', display: true},
            				{left: '$', right: '$', display: false},
          			],
          			// • rendering keys, e.g.:
          			throwOnError : false
        			});
      			});
    		</script>
  """

socialIcons = [
	{name = 'linkedin', url = 'https://www.linkedin.com/in/elias-braun-37b3b6272/'},
    	{name = 'instagram', url = 'https://www.instagram.com/elias_.private/'},
    	{name = 'email', url = 'mailto:braunelias@tghd.email'},
  	{name = 'gitlab', url  = 'https://gitlab.tghd.dev/explore'},
	{name = 'github', url = 'https://github.com/TechnicGamerHD'}
]
metaKeywords = ['blog', 'hugo', 'RoboCup']

[menu]
	[[menu.main]]
    		name = 'Home'
    		pre = "<span data-feather='home'></span>"
    		url = '/'
    		weight = 1
	  [[menu.main]]
    		name = "Projects"
    		pre = "<span data-feather='code'></span>"
    		url = "/projects/"
    		weight = 2
 	[[menu.main]]
    		identifier = "github"
    		pre = "<span data-feather='github'></span>"
    		url = "https://github.com/TechnicGamerHD/personalSite"
    		weight = 3

[markup]
  	[markup.tableOfContents]
    		startLevel = 1
    		endLevel = 4
    		ordered = false
